apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Release.Name }}-orders
subsets:
  - addresses:
    - ip: {{ .Values.orders.loadBalancerIp }}
    ports:
    - port: {{ .Values.orders.targetPort }}